file1= open('codingal.txt','r')
file2=open('filehandling2.txt','r')
content1=file1.read()
content2=file2.read()
print(content1)
print(content2)
file1.close()
file2.close()
file1=open('codingal.txt','a+')
file2=open('filehandling2.txt','r')
file1.write(file2.read())
print('content file after appending')
print(file1.read())
print(file2.read())

